config/routes.rb
Shinema::Application.routes.draw do
  resources :videos

  root 'videos#index'

  get 'search' => 'videos#search', as: :search

  get 'all' => 'videos#all'

  

end

app/models/video.rb
class Video
  include Mongoid::Attributes::Dynamic, Mongoid::Document  
  field :title, type: String
  field :link, type: String

  attr_accessor :accessible

  private
  	def mass_assignment_authorizer(role = :default)
		super + (accessible || [])
	end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/videos_controller.rb
class VideosController < ApplicationController
  before_action :set_video, only: [:show, :edit, :update, :destroy]

  # GET /search
  def search
	#@videos = Video.search(params[:search])
	puts params[:search]
	@videos = Video.where(title: /.*#{params[:search]}.*/)
	puts "videos: "
	puts @videos
  end

  # GET /videos
  # GET /videos.json
  def index
    @videos = Video.all
  end

  # GET /videos
  # GET /videos.json
  def all
    @videos = Video.all
  end

  # GET /videos/1
  # GET /videos/1.json
  def show
  end

  # GET /videos/new
  def new
    @video = Video.new
  end

  # GET /videos/1/edit
  def edit
  end

  # POST /videos
  # POST /videos.json
  def create
    @video = Video.new

	@video.accessible = VideoConfig::DYNAMIC_FIELDS['attributes'].keys

    puts "keys"	
	for key in VideoConfig::DYNAMIC_FIELDS['attributes'].keys
		puts key
	end

	@video.attributes = video_params

    respond_to do |format|
      if @video.save
        format.html { redirect_to @video, notice: 'Video was successfully created.' }
        format.json { render action: 'show', status: :created, location: @video }
      else
        format.html { render action: 'new' }
        format.json { render json: @video.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /videos/1
  # PATCH/PUT /videos/1.json
  def update
    respond_to do |format|
      if @video.update(video_params)
        format.html { redirect_to @video, notice: 'Video was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @video.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /videos/1
  # DELETE /videos/1.json
  def destroy
    @video.destroy
    respond_to do |format|
      format.html { redirect_to videos_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_video
      @video = Video.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def video_params
	  # This is probably bad, change it later
      params.require(:video).permit!
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/videos_helper.rb
module VideosHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Shinema</title>
  <%= stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true %>
  <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/videos/_form.html.erb
<%= form_for(@video) do |f| %>
  <% if @video.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@video.errors.count, "error") %> prohibited this video from being saved:</h2>

      <ul>
      <% @video.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>


  <div class="field">
		<%= f.label :title %><br>
		<%= f.text_field :title %>
  </div>

  <div class="field">
		<%= f.label :link %><br>
		<%= f.text_field :link %>
  </div>

  <% EventConfig::DYNAMIC_FIELDS['attributes'].keys.each do |attribute| %>
	<div class="field">
		<label><%= attribute %></label><br>
		<input id="video_<%= attribute %>" name="video[<%= attribute %>]" type="text" />
	</div>
  <% end %>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/videos/all.html.erb
<h1>Listing videos</h1>

<table>
  <thead>
    <tr>
      <th>Title</th>
      <th>Link</th>
      <th></th>
      <th></th>
      <th></th>
    </tr>
  </thead>

  <tbody>
    <% @videos.each do |video| %>
      <tr>
        <td><%= video.title %></td>
		<td><a href="<%= video.link %>"><%= video.link %></a></td>
        <td><%= link_to 'Show', video %></td>
        <td><%= link_to 'Edit', edit_video_path(video) %></td>
        <td><%= link_to 'Destroy', video, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Video', new_video_path %>

app/views/videos/edit.html.erb
<h1>Editing video</h1>

<%= render 'form' %>

<%= link_to 'Show', @video %> |
<%= link_to 'Back', videos_path %>

app/views/videos/index.html.erb
<h1>Find video:</h1>

<%= form_tag search_path, :method => 'get' do %>
  <p>
    <%= text_field_tag :search, params[:search] %>
	<% VideoConfig::DYNAMIC_FIELDS.each do |key, value| %>
		<%= collection_select :sfield, value, value, :to_s, :to_s, 
			:prompt => true %>
	<% end %>
    <%= submit_tag "Search", :name => nil %>
  </p>
<% end %>

<table>
  <thead>
    <tr>
      <th>Title</th>
      <th>Link</th>
      <th></th>
      <th></th>
      <th></th>
    </tr>
  </thead>

  <tbody>
    <% @videos.each do |video| %>
      <tr>
        <td><%= video.title %></td>
		<td><a href="<%= video.link %>"><%= video.link %></a></td>
        <td><%= link_to 'Show', video %></td>
        <td><%= link_to 'Edit', edit_video_path(video) %></td>
        <td><%= link_to 'Destroy', video, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Video', new_video_path %>

app/views/videos/new.html.erb
<h1>New video</h1>

<%= render 'form' %>

<%= link_to 'Back', videos_path %>

app/views/videos/search.html.erb
<h1>Find video:</h1>

<table>
  <thead>
    <tr>
      <th>Title</th>
      <th>Link</th>
      <th></th>
      <th></th>
      <th></th>
    </tr>
  </thead>

  <tbody>
    <% @videos.each do |video| %>
      <tr>
        <td><%= video.title %></td>
		<td><a href="<%= video.link %>"><%= video.link %></a></td>
        <td><%= link_to 'Show', video %></td>
        <td><%= link_to 'Edit', edit_video_path(video) %></td>
        <td><%= link_to 'Destroy', video, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Video', new_video_path %>

app/views/videos/show.html.erb
<p id="notice"><%= notice %></p>

<% @video.attributes.each do |attr_name, attr_value| %>
	<% if attr_name != "_id" %> 
		<p>
		<strong> <%= attr_name %> </strong>
		<%= attr_value %>
		</p>
	<% end %>
<% end %>

<%= link_to 'Edit', edit_video_path(@video) %> |
<%= link_to 'Back', videos_path %>